title: திருவேங்கடம்
# subtitle: "Version 2.0"
title_separator: "|"
name: "திருவேங்கடம் சத்தியசீலன்"
email: thiru.dev@hotmail.com
description: >- # this means to ignore newlines until "baseurl:".
url: https://thiru.blog
# baseurl: /
repository: sunthiru/thiru.blog
minimal_mistakes_skin: dark

# search settings
search: true
search_provider: algolia
algolia:
  application_id: ZH1JRSOIOK
  index_name: thiru_tamil_blog_index
  search_only_api_key: e4cf5b6877646ad0b10d1e31be8890da
  powered_by : true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
logo: "/assets/images/logo.png"
timezone: Asia/Calcutta
locale: ta-IN
# breadcrumbs: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

author:
  name   : "திருவேங்கடம் சத்தியசீலன்"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "மின்னஞ்சல்"
      icon: "far fa-envelope"
      url: "mailto:thiru.dev@hotmail.com"

# Collections
collections:
  finfreedom:
    output: true
    permalink: /:collection/:title/

footer:
  links:
     - label: "மின்னஞ்சல்"
       icon: "far fa-envelope"
       url: "mailto:thriu.blog@outlook.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
      words_per_minute: 100
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      words_per_minute: 100
      related: false
      show_date: true
  # _collections
  - scope:
      path: ""
      type: finfreedom
    values:
      layout: single
      read_time: true
      words_per_minute: 100
      author_profile: false
      share: false
      related: false
      show_date: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Y54H7SFJGM"
    anonymize_ip: true # default
